### ISSUE TITLE
.c files don't build on Windows.

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lake#118]
See [Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/Lake.20and.20'cc')

Repro on Windows (not MSYS2):
```
git clone https://github.com/xubaiw/CMark.lean/
cd CMark.lean
lake build
error: failed to execute `cc`: no such file or directory
```

Seems problematic that this action is hard coded to use "cc" rather than `leanInstall.cc`.  On Windows leanInstall.cc is wired to `clang.exe` which is perfect.  So why doesn't the following use that leanInstall setup?

```lean
def compileO (name : String) (oFile srcFile : FilePath)
(moreArgs : Array String := #[]) (compiler : FilePath := "cc") : LogIO Unit := do
  logInfo s!"Compiling {name}"
  createParentDirs oFile
  proc {
    cmd := compiler.toString
    args := #["-c", "-o", oFile.toString, srcFile.toString] ++ moreArgs
  }
```

Interestingly the Lake/examples/ffi example builds on windows because it uses *.cpp instead of *.c and *.cpp does use clang.exe.  But if you change the ffi example to use .c instead you get the same error as CMark.lean.

**Comment by Kha** [comment]
This is as intended. The `leanc` C compiler is not meant to be used for anything other than compiling Lean-generated files, and will likely be replaced by https://github.com/leanprover/lean4/pull/1497 anyway.

**Comment by lovettchris** [comment]
Is this also true for an ffi plugin that will be loaded in the lean process?  How do you endure compatible C++ ABI and C runtimes and and all that?

**Comment by Kha** [comment]
> How do you ensure compatible C++ ABI and C runtimes and and all that?

By carefully adjusting linker flags etc. We don't have a special answer there.

> note the lake ffi sample does use leanc, but only because the c file is ffi.cpp

I don't know why that is, it does pass `compiler := "c++"` at https://github.com/leanprover/lake/blob/6cfb4e3fd7ff700ace8c2cfdb85056d59f321920/examples/ffi/lib/lakefile.lean#L20

**Comment by lovettchris** [comment]
Thanks, Sebasitan, you cleared this up.  I was wrongly thinking the clang we ship in the leantoolchain can also be used to build ffi plugins, but it is not a complete version of clang, it is stripped down minimal just enough to build .lean generated .c code.  So if my ffi plugin contains complex C or C++ code then that version of clang would not be sufficient.  

One day it would be nice to have a Windows native build of Lean and Lake and ffi plugins all using the Visual Studio compiler.  If Lean was a pure "cmake" project I could do this already, but alas it isn't.

**Comment by tydeu** [comment]
Great! It seems everything has been resolved here. So, I will close this issue.

**Comment by lovettchris** [comment]
Well not exactly, we still have a big hole in windows support for Lake where Lake cannot properly compile an FFI extension unless you are inside an MSYS environment with clang available. This should at least be documented somewhere.

**Comment by tydeu** [comment]
@lovettchris The MSYS requirement is not a limitation of Lake, though -- it is a limitation of Lean. Thus, it should probably be documented in the FFI section of the Lean manual. Also, you don't need clang to build FFI extensions. I just use the builtin MSYS2 `c++` (which I am pretty sure is GCC) and it works.

**Comment by lovettchris** [comment]
True and I see that lake is hard coded to call out to `cc` in the `compileO` action and `ar` for linking libraries in `compileStaticLib`.  I think Lake has a bug when I try and compile a .cpp file in an FFI module because it then calls `leanc` for that. Perhaps it should be configurable as to whether you want to use gcc, clang, or cl.exe on Windows?  But perhaps we can never get MSVC compatibility until we have a full cmake build for Lean itself with no bash shell scripts calling out to `clang`.

**Comment by tydeu** [comment]
@lovettchris 

> True and I see that lake is hard coded to call out to `cc` in the `compileO` action and `ar` for linking libraries in `compileStaticLib`.

No it is not, those are parameters that default to `cc` / `ar`, but a user change use different settings when writing FFI code (like the FFI example does).

**Comment by lovettchris** [comment]
Ah, I see, thanks.
